In [1]:
import numpy as np

In [2]:
a=np.random.randint(1,10,(3,4))
print(a)

[[1 6 6 5]
 [6 1 6 8]
 [1 6 3 3]]


# np.reshape(array,(rows,cols),order)-->returns new array after reshaping

In [4]:
np.reshape(a,(4,3),order='c') #row major(same as in C- language)

array([[1, 6, 6],
       [5, 6, 1],
       [6, 8, 1],
       [6, 3, 3]])

In [5]:
np.reshape(a,(4,3),order='f') #column major(same as in fortran- language)

array([[1, 1, 3],
       [6, 6, 5],
       [1, 6, 8],
       [6, 6, 3]])

In [6]:
np.reshape(a,(4,3)) #default order='c'

array([[1, 6, 6],
       [5, 6, 1],
       [6, 8, 1],
       [6, 3, 3]])

In [7]:
np.reshape(a,(3,3))

ValueError: cannot reshape array of size 12 into shape (3,3)

In [14]:
np.reshape(a,(-1,2)) #-1 means unknown dimension,and it will be auto computed based on other dim

array([[1, 6],
       [6, 5],
       [6, 1],
       [6, 8],
       [1, 6],
       [3, 3]])

In [15]:
print(a)

[[1 6 6 5]
 [6 1 6 8]
 [1 6 3 3]]


# np.resize(array,(rows,cols))

In [18]:
np.resize(a,(4,3)) #default order is 'c' and we can not pass this order

array([[1, 6, 6],
       [5, 6, 1],
       [6, 8, 1],
       [6, 3, 3]])

In [19]:
np.resize(a,(4,-1)) #-ve(unknown dim is not allowed)

ValueError: all elements of `new_shape` must be non-negative

In [22]:
np.resize(a,(4,4))

array([[1, 6, 6, 5],
       [6, 1, 6, 8],
       [1, 6, 3, 3],
       [1, 6, 6, 5]])

In [23]:
np.resize(a,(4,2))

array([[1, 6],
       [6, 5],
       [6, 1],
       [6, 8]])

# array.flatten(order)--->returns 1d array of given array

In [27]:
print(a)

[[1 6 6 5]
 [6 1 6 8]
 [1 6 3 3]]


In [24]:
a.flatten(order='c')

array([1, 6, 6, 5, 6, 1, 6, 8, 1, 6, 3, 3])

In [25]:
a.flatten(order='f')

array([1, 6, 1, 6, 1, 6, 6, 6, 3, 5, 8, 3])

In [26]:
a.flatten()  #row major

array([1, 6, 6, 5, 6, 1, 6, 8, 1, 6, 3, 3])

# Array Operations
- ##### Operators
- ##### Numpy functions
- ##### Array methods
- ##### Array attributes

In [28]:
print(a)

[[1 6 6 5]
 [6 1 6 8]
 [1 6 3 3]]


In [30]:
#Operators
print(a+2)
print(a-2)
print(a*2)

[[ 3  8  8  7]
 [ 8  3  8 10]
 [ 3  8  5  5]]
[[-1  4  4  3]
 [ 4 -1  4  6]
 [-1  4  1  1]]
[[ 2 12 12 10]
 [12  2 12 16]
 [ 2 12  6  6]]


In [31]:
# Numpy functions
print(np.sum(a))
print(np.mean(a))

52
4.333333333333333


In [32]:
# Array methods
print(a.sum())
print(a.mean())

52
4.333333333333333


In [35]:
print(np.median(a))
#print(a.median())   #error(there is no such method in array)

5.5


In [38]:
print(a.flatten()) 
#print(np.flatten(a)) #error(there is no such function in numpy)

[1 6 6 5 6 1 6 8 1 6 3 3]


In [42]:
# Array attributes
print(a.ndim)
print(a.shape)
print(a.size)

2
(3, 4)
12


In [43]:
print(np.shape(a))

(3, 4)


In [45]:
x=[[1,2,3],[4,5,6],[7,8,9],[1,1,1]]
#print(x.shape)
print(np.shape(x))

(4, 3)


# Pandas
- ##### It is another library to perform statistical & time series related operations.
- ##### It is a 3rd party library first released in 2008.
- ##### It represents 1d and 2d data with labels.
- ##### It provides 2 new datatypes
  - DataFrame
  - Series

In [46]:
import pandas as pd

# DataFrame
- ##### It represents 2d data with labels
- ##### It is mutable

#### Creation of DataFrame
- ##### 2d array like(list of list/list of tuples/numpy 2d array)
- ##### from dict
- ##### from excel file
- ##### from csv file
- ##### from database table
- ##### from html table
- etc.

In [47]:
#empty
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [48]:
#2d array like
df=pd.DataFrame(data=[[1,25,89],[2,23,85],[3,23,70]])
df

0   1   2
0  1  25  89
1  2  23  85
2  3  23  70

In [50]:
#2d array like
df=pd.DataFrame(data=[[1,25,89],[2,23,85],[3,23,70]],columns=['roll','age','marks'],index=['a','b','c'])
df

roll  age  marks
a     1   25     89
b     2   23     85
c     3   23     70

In [52]:
#2d array like
df=pd.DataFrame(data=[[1,25,89],[2,23,85],[3,23,70]],columns=['roll',10,9.8],index=['a',1,1.1])
df

roll  10  9.8
a       1  25   89
1       2  23   85
1.1     3  23   70

In [53]:
#from dict
df=pd.DataFrame(data={'roll':[1,2,3],'age':[20,18,22],'marks':[80,87,90]})
df

roll  age  marks
0     1   20     80
1     2   18     87
2     3   22     90

In [54]:
#from excel file
df=pd.read_excel('c:/abc/students.xlsx',sheet_name='Sheet1')
df

sonu  1  20
0    monu  2  19
1  chintu  3  22

In [55]:
df=pd.read_excel('c:/abc/students.xlsx',sheet_name='Sheet1',header=None)
df

0  1   2
0    sonu  1  20
1    monu  2  19
2  chintu  3  22

In [56]:
df=pd.read_excel('c:/abc/students.xlsx',sheet_name='Sheet1',header=None,names=['Name','Roll','Age'])
df

Name  Roll  Age
0    sonu     1   20
1    monu     2   19
2  chintu     3   22

In [58]:
df=pd.read_excel('c:/abc/students.xlsx',sheet_name='Sheet2')
df

Name  Roll  Age
0    sonu     1   20
1    monu     2   19
2  chintu     3   22

In [62]:
df=pd.read_excel('c:/abc/students.xlsx',sheet_name='Sheet2')
print(df)

     Name  Roll  Age
0    sonu     1   20
1    monu     2   19
2  chintu     3   22


In [63]:
df

Name  Roll  Age
0    sonu     1   20
1    monu     2   19
2  chintu     3   22

In [65]:
df=pd.read_excel('c:/abc/students.xlsx',sheet_name=1)
df

Name  Roll  Age
0    sonu     1   20
1    monu     2   19
2  chintu     3   22

In [66]:
df=pd.read_excel('c:/abc/students.xlsx') #defualt sheet_name=0
df

sonu  1  20
0    monu  2  19
1  chintu  3  22

In [67]:
dict_dfs=pd.read_excel('c:/abc/students.xlsx',sheet_name=None) #it will read all sheets

In [68]:
dict_dfs.keys()

dict_keys(['Sheet1', 'Sheet2'])

In [69]:
df1=dict_dfs['Sheet1']
df2=dict_dfs['Sheet2']

In [70]:
df1

sonu  1  20
0    monu  2  19
1  chintu  3  22

In [71]:
df2

Name  Roll  Age
0    sonu     1   20
1    monu     2   19
2  chintu     3   22