In [2]:
x=[10,20,30,40]
y=[]
for i in x:
    y.append(i+5)
y

[15, 25, 35, 45]

In [3]:
import numpy as np

In [5]:
x=np.array([10,20,30,40])
print(x)
y=x+5
print(y)

[10 20 30 40]
[15 25 35 45]


In [23]:
x=np.array([10,20,30,40,5,12,39])
print(x)
print(x[0])
print(x[:3])
print(x[x>25])
print(x[(x>25) | (x%2==0)])
print(x[(x>25) & (x%2==0)])

[10 20 30 40  5 12 39]
10
[10 20 30]
[30 40 39]
[10 20 30 40 12 39]
[30 40]


# Creating of Numpy 2D Array(Matrix)

In [27]:
a=np.array([[1,2,3],[2,3,4],[4,5,6],[1,2,1]])
print(a)

[[1 2 3]
 [2 3 4]
 [4 5 6]
 [1 2 1]]


In [28]:
a=np.zeros((4,3)) #(rows,cols)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
#How to access a value in matrix
#1. array[row_index][col_index]
#2. array[row_index,col_index]
a[2][-1]=5
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 5.]
 [0. 0. 0.]]


In [31]:
print(a[2,-1])
a[1,0]=10
print(a)

5.0
[[ 0.  0.  0.]
 [10.  0.  0.]
 [ 0.  0.  5.]
 [ 0.  0.  0.]]


In [32]:
a=np.ones((3,3))#(r,c)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [33]:
a=np.full((3,3),100)#(r,c),initial_value
print(a)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [34]:
a=np.random.randint(1,10,(3,3)) #low,high,(r,c)
print(a)

[[4 6 2]
 [2 3 1]
 [6 5 7]]


In [35]:
a=np.random.uniform(1,10,(3,3))#low,high,(r,c) for floating values
print(a)

[[8.13851868 9.92687447 8.60190986]
 [8.20920681 6.98825024 2.28615081]
 [6.22710119 9.15877659 8.0632498 ]]


In [36]:
a=np.eye(3,3) #(r,c) #identity matrix
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Numpy to perform statistical operations

In [37]:
a=np.random.randint(1,10,20)
print(a)

[7 3 1 8 4 3 9 1 7 7 3 8 6 4 6 1 8 7 9 4]


In [56]:
print(np.sum(a))
print(np.mean(a)) #arithmetic average
print(np.median(a)) 
print(np.quantile(a,[.25,.50,.75])) 
print(np.quantile(a,[.20,.40,.60,.80])) 
print(np.std(a))
print(np.max(a))
print(np.min(a))
print(np.argmin(a))     #returns lowest index of min value
print(np.where(a==7))   #returns all indexes of values where condition is True
print(np.where(a<5))    #returns all indexes of values where condition is True
print(np.where(a==np.min(a))) 
print(np.argmax(a))     #returns lowest index of max value

106
5.3
6.0
[3.   6.   7.25]
[3. 4. 7. 8.]
2.628687885618983
9
1
2
(array([ 0,  8,  9, 17], dtype=int64),)
(array([ 1,  2,  4,  5,  7, 10, 13, 15, 19], dtype=int64),)
(array([ 2,  7, 15], dtype=int64),)
6


# Statistical operations with matrix

In [57]:
a=np.random.randint(1,10,(3,4))
print(a)

[[7 9 5 1]
 [4 5 9 4]
 [9 3 7 2]]


In [64]:
print(np.sum(a))         #sum of all values
print(np.sum(a,axis=1))  #row-wise sum
print(np.sum(a,axis=0))  #col-wise sum

print(np.min(a))         #min in matrix
print(np.min(a,axis=1))  #min in each row
print(np.min(a,axis=0))  #min in each col

print(np.argmin(a))      #first flatten the matrix(converted to 1d array) then returns index of min value
print(np.argmin(a,axis=1))
print(np.argmin(a,axis=0))

65
[22 22 21]
[20 17 21  7]
1
[1 4 2]
[4 3 5 1]
3
[3 0 3]
[1 2 0 0]


# matrix related operations

In [65]:
print(a)

[[7 9 5 1]
 [4 5 9 4]
 [9 3 7 2]]


In [66]:
print(np.transpose(a)) #rows-->converted to columns ,returns new matrix

[[7 4 9]
 [9 5 3]
 [5 9 7]
 [1 4 2]]


In [69]:
print(a*2) #returns a new matrix

[[14 18 10  2]
 [ 8 10 18  8]
 [18  6 14  4]]


In [70]:
print(a[a>5]) #returns 1d array

[7 9 9 9 7]


In [71]:
a=np.array([[1,2],[2,3]])
b=np.array([[2,1],[2,2]])
print(a)
print(b)

[[1 2]
 [2 3]]
[[2 1]
 [2 2]]


In [72]:
print(np.dot(a,b))

[[ 6  5]
 [10  8]]


In [73]:
a*b  #element by element multiply not dot product

array([[2, 2],
       [4, 6]])

In [75]:
print(a@b)  #dot product same as np.dot(a,b)

[[ 6  5]
 [10  8]]


In [76]:
print(b@a)

[[ 4  7]
 [ 6 10]]


# Array Attributes to find Meta Information
- are variables/properties of array object that provides various information like dim,shape,size,dtype of array.

In [79]:
a=np.random.randint(1,10,(3,4))
print(a)

[[8 7 1 6]
 [7 7 8 4]
 [7 3 9 6]]


In [82]:
print(a.ndim)
print(a.dtype)
print(a.shape)
print(a.size)

2
int32
(3, 4)
12
